# Generated by Django 3.2.3 on 2021-05-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_logmessage_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='LogMessage',
        ),
    ]
