# Generated by Django 3.2.3 on 2021-05-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_customer_logmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogMessage',
            new_name='Customer',
        ),
    ]
